// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxydi9XNdwxqwQ7EYppXIU9YQMeKl0Pwk',
    appId: '1:264666782957:web:faca9b252309524a2880e4',
    messagingSenderId: '264666782957',
    projectId: 'counselling-cell-app-007',
    authDomain: 'counselling-cell-app-007.firebaseapp.com',
    storageBucket: 'counselling-cell-app-007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPW7il8H32t9JUPpr5ze3lYKiys_ALFd4',
    appId: '1:264666782957:android:c150b4197abc801e2880e4',
    messagingSenderId: '264666782957',
    projectId: 'counselling-cell-app-007',
    storageBucket: 'counselling-cell-app-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZL7paMFmjyuGfPEHLCsXAfVOHuCM0W8',
    appId: '1:264666782957:ios:351000eef8d1e6f32880e4',
    messagingSenderId: '264666782957',
    projectId: 'counselling-cell-app-007',
    storageBucket: 'counselling-cell-app-007.appspot.com',
    iosClientId: '264666782957-6g5r7snu1pdn81rh97m4dp79345q8ede.apps.googleusercontent.com',
    iosBundleId: 'com.example.counselingCellApp',
  );
}
